---
volumes:
  step-db: {}

services:
  step-ca:
    image: mafrosis/step-ca:${STEP_CERTS_VERSION}
    command: /etc/step-ca/config/ca.json
    build:
      context: .
      args:
        STEP_VERSION: ${STEP_VERSION}
        STEP_CERTS_VERSION: ${STEP_CERTS_VERSION}
    restart: unless-stopped
    ports:
      - 4433:443
    volumes:
      - ./step-config:/etc/step-ca
      - step-db:/etc/step-ca/db
      - /var/run/pcscd/pcscd.comm:/var/run/pcscd/pcscd.comm
    env_file:
      - .secrets
